export const amazonCoupons = [
    {
      id: 1,
      logoSrc: 'https://i.postimg.cc/g2zJZLZY/amazon.png',
      title: 'Save 10% on Your Next Purchase',
      code: 'AMAZON10OFF',
      validTill: '20 Dec, 2022',
      cardColor: 'linear-gradient(135deg, #7158fe, #9d4de6)',
      store: 'amazon',
    },
    {
      id: 2,
      logoSrc: 'https://i.postimg.cc/g2zJZLZY/amazon.png',
      title: '$15 Off Your Order of $50 or More',
      code: 'HOLIDAY15',
      validTill: '31 Dec, 2022',
      cardColor: 'linear-gradient(135deg, #ff5733, #ff8c33)',
      store: 'amazon',
    },
    {
      id: 3,
      logoSrc: 'https://i.postimg.cc/g2zJZLZY/amazon.png',
      title: 'Free Shipping on All Electronics',
      code: 'FREESHIP-ELEC',
      validTill: '15 Jan, 2023',
      cardColor: 'linear-gradient(135deg, #00bcd4, #009688)',
      store: 'amazon',
    },
    {
      id: 4,
      logoSrc: 'https://i.postimg.cc/g2zJZLZY/amazon.png',
      title: '50% Off Amazon Prime Membership',
      code: 'PRIME50OFF',
      validTill: '28 Feb, 2023',
      cardColor: 'linear-gradient(135deg, #ff9800, #ff5722)',
      store: 'amazon',
    },
    {
      id: 5,
      logoSrc: 'https://i.postimg.cc/g2zJZLZY/amazon.png',
      title: 'Amazon Fresh: $10 Off Your First Order',
      code: 'FRESH10FIRST',
      validTill: '10 Mar, 2023',
      cardColor: 'linear-gradient(135deg, #9c27b0, #673ab7)',
      store: 'amazon',
    },
    {
      id: 6,
      logoSrc: 'https://i.postimg.cc/g2zJZLZY/amazon.png',
      title: 'Buy 2, Get 1 Free on Books',
      code: 'BOOKS-B2G1',
      validTill: '05 Apr, 2023',
      cardColor: 'linear-gradient(135deg, #2196f3, #03a9f4)',
      store: 'amazon',
    },
    {
      id: 7,
      logoSrc: 'https://i.postimg.cc/g2zJZLZY/amazon.png',
      title: 'Extra 30% Off Amazon Basics',
      code: 'BASICS30',
      validTill: '20 May, 2023',
      cardColor: 'linear-gradient(135deg, #4caf50, #8bc34a)',
      store: 'amazon',
    },
    {
      id: 8,
      logoSrc: 'https://i.postimg.cc/g2zJZLZY/amazon.png',
      title: 'Amazon Fashion: $25 Off Orders Over $100',
      code: 'FASHION25',
      validTill: '15 Jun, 2023',
      cardColor: 'linear-gradient(135deg, #ffeb3b, #ffc107)',
      store: 'amazon',
    },
    {
      id: 9,
      logoSrc: 'https://i.postimg.cc/g2zJZLZY/amazon.png',
      title: 'Home & Kitchen: Buy 1, Get 1 50% Off',
      code: 'HOME50OFF',
      validTill: '30 Jun, 2023',
      cardColor: 'linear-gradient(135deg, #795548, #a1887f)',
      store: 'amazon',
    },
    {
      id: 10,
      logoSrc: 'https://i.postimg.cc/g2zJZLZY/amazon.png',
      title: 'Amazon Prime Day Exclusive: Save Big!',
      code: 'PRIMEDAY2023',
      validTill: '15 Jul, 2023',
      cardColor: 'linear-gradient(135deg, #e91e63, #f44336)',
      store: 'amazon',
    },
  ];
