export const flipkartCoupons = [
    {
    id: 1,
    logoSrc: 'https://i.postimg.cc/BvwXsZtJ/flipkart.png',
    title: 'Flat 15% Off on Electronics',
    code: 'ELEC15OFF',
    validTill: '31 Dec, 2022',
    cardColor: 'linear-gradient(135deg, #ff5733, #ff8c33)',
    store: 'flipkart',
    },
    {
    id: 2,
    logoSrc: 'https://i.postimg.cc/BvwXsZtJ/flipkart.png',
    title: 'Big Billion Days Sale: Up to 70% Off',
    code: 'BIGSALE2022',
    validTill: '15 Jan, 2023',
    cardColor: 'linear-gradient(135deg, #00bcd4, #009688)',
    store: 'flipkart',
    },
    {
    id: 3,
    logoSrc: 'https://i.postimg.cc/BvwXsZtJ/flipkart.png',
    title: 'Fashion Fiesta: Extra 20% Off',
    code: 'FASHION20',
    validTill: '28 Feb, 2023',
    cardColor: 'linear-gradient(135deg, #ff9800, #ff5722)',
    store: 'flipkart',
    },
    {
    id: 4,
    logoSrc: 'https://i.postimg.cc/BvwXsZtJ/flipkart.png',
    title: 'Home & Kitchen Bonanza: Save 25%',
    code: 'HOME25SALE',
    validTill: '10 Mar, 2023',
    cardColor: 'linear-gradient(135deg, #9c27b0, #673ab7)',
    store: 'flipkart',
    },
    {
    id: 5,
    logoSrc: 'https://i.postimg.cc/BvwXsZtJ/flipkart.png',
    title: 'Flipkart Supermart: Rs. 100 Off',
    code: 'SUPERMART100',
    validTill: '05 Apr, 2023',
    cardColor: 'linear-gradient(135deg, #2196f3, #03a9f4)',
    store: 'flipkart',
    },
    {
    id: 6,
    logoSrc: 'https://i.postimg.cc/BvwXsZtJ/flipkart.png',
    title: 'Buy 1 Get 1 Free on Books',
    code: 'BOGOBOOKS',
    validTill: '20 May, 2023',
    cardColor: 'linear-gradient(135deg, #4caf50, #8bc34a)',
    store: 'flipkart',
    },
    {
    id: 7,
    logoSrc: 'https://i.postimg.cc/BvwXsZtJ/flipkart.png',
    title: 'Mobile Madness Sale: Extra 10% Off',
    code: 'MOBILE10OFF',
    validTill: '15 Jun, 2023',
    cardColor: 'linear-gradient(135deg, #ffeb3b, #ffc107)',
    store: 'flipkart',
    },
    {
    id: 8,
    logoSrc: 'https://i.postimg.cc/BvwXsZtJ/flipkart.png',
    title: 'Fitness Gear: 30% Off',
    code: 'FITNESS30',
    validTill: '30 Jun, 2023',
    cardColor: 'linear-gradient(135deg, #795548, #a1887f)',
    store: 'flipkart',
    },
    {
    id: 9,
    logoSrc: 'https://i.postimg.cc/BvwXsZtJ/flipkart.png',
    title: 'Flipkart Plus Member Exclusive: 50% Off',
    code: 'PLUS50OFF',
    validTill: '15 Jul, 2023',
    cardColor: 'linear-gradient(135deg, #e91e63, #f44336)',
    store: 'flipkart',
    },
    {
    id: 10,
    logoSrc: 'https://i.postimg.cc/BvwXsZtJ/flipkart.png',
    title: 'Electronics Clearance Sale: Up to 40% Off',
    code: 'ELECCLEAR40',
    validTill: '31 Jul, 2023',
    cardColor: 'linear-gradient(135deg, #673ab7, #9c27b0)',
    store: 'flipkart',
    },
    ];