export const zomatoCoupons = [
  {
    id: 1,
    logoSrc: 'https://i.postimg.cc/DfbjYrp1/Zomato-company-logo.png',
    title: 'Zomato Food Festival: Up to 60% Off',
    code: 'FOOD60',
    validTill: '31 Dec, 2022',
    cardColor: 'linear-gradient(135deg, #ff5733, #ff8c33)',
    store: 'zomato',
  },
  {
    id: 2,
    logoSrc: 'https://i.postimg.cc/DfbjYrp1/Zomato-company-logo.png',
    title: 'Flat 25% Off on Food Orders',
    code: 'FOOD25',
    validTill: '15 Jan, 2023',
    cardColor: 'linear-gradient(135deg, #00bcd4, #009688)',
    store: 'zomato',
  },
  {
    id: 3,
    logoSrc: 'https://i.postimg.cc/DfbjYrp1/Zomato-company-logo.png',
    title: 'Zomato End of Season Sale: Extra 20% Off',
    code: 'EOSS20',
    validTill: '28 Feb, 2023',
    cardColor: 'linear-gradient(135deg, #ff9800, #ff5722)',
    store: 'zomato',
  },
  {
    id: 4,
    logoSrc: 'https://i.postimg.cc/DfbjYrp1/Zomato-company-logo.png',
    title: 'Buy 2 Get 1 Free on Food Items',
    code: 'FOODBOGO',
    validTill: '10 Mar, 2023',
    cardColor: 'linear-gradient(135deg, #9c27b0, #673ab7)',
    store: 'zomato',
  },
  {
    id: 5,
    logoSrc: 'https://i.postimg.cc/DfbjYrp1/Zomato-company-logo.png',
    title: 'Zomato Snacks: 30% Off',
    code: 'SNACKS30',
    validTill: '05 Apr, 2023',
    cardColor: 'linear-gradient(135deg, #2196f3, #03a9f4)',
    store: 'zomato',
  },
  // Add more Zomato coupons here with unique IDs
];
